AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM template to deploy a GoLang Lambda function using Gin framework.

Globals:
  Function:
    Runtime: provided.al2023
    Timeout: 10

Resources:
  TarotDrawFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TarotDrawFunction
      Handler: main
      CodeUri: .
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            ApiId: !Ref TarotApi
        DrawPost:
          Type: HttpApi
          Properties:
            Path: /draw
            Method: POST
            ApiId: !Ref TarotApi
        LicenseGet:
          Type: HttpApi
          Properties:
            Path: /license
            Method: GET
            ApiId: !Ref TarotApi

  TarotApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: "'*'"
        AllowHeaders: "'Content-Type'"
        AllowMethods: "'GET,POST,OPTIONS'"

  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/api-gateway/${TarotApi}/logs"
      RetentionInDays: 7
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint URL for the Prod stage"
    Value: !Sub "https://${TarotApi}.execute-api.${AWS::Region}.amazonaws.com/"
  TarotDrawFunctionArn:
    Description: "Tarot Draw Function ARN"
    Value: !GetAtt TarotDrawFunction.Arn
