apiVersion: v1
kind: Service
metadata:
  name: {{ include "tarot-shuffle-draw.fullname" . }}
  labels:
    {{- include "tarot-shuffle-draw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "tarot-shuffle-draw.selectorLabels" . | nindent 4 }}
